services:
  mysql:
    image: mysql:8.0
    container_name: ytb2bili-mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: your_password
      MYSQL_DATABASE: bili_up
      MYSQL_USER: ytb2bili
      MYSQL_PASSWORD: ytb2bili@123
    volumes:
      - ./mysql_data:/var/lib/mysql
    ports:
      - "3309:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-pyour_password"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  ytb2bili:
    image: difyz9/ytb2bili:latest   # 直接使用 Docker Hub 预构建镜像
    container_name: ytb2bili-app
    restart: unless-stopped
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8096:8096"
    volumes:
      - ./config.toml:/app/config.toml
      - ./logs:/app/do
      - ./downloads:/app/downloads
    environment:
      - TZ=Asia/Shanghai




# docker compose down
# docker volume rm ytb2bili_mysql_data
